%web_drop_table(WORK.ALLMERGE);


FILENAME REFFILE '/home/isaias.prestes/Data/2014 2015 2016 Merge AGS-Exames 19-02-18 ELEGIVEIS_CCP_PCR_ALB_EXAMES_ LIMPO_24.04.sav';

PROC IMPORT DATAFILE=REFFILE
	DBMS=SAV
	OUT=WORK.ALLMERGE;
RUN;

PROC CONTENTS DATA=WORK.ALLMERGE; RUN;


%web_open_table(WORK.ALLMERGE);


/* Generated Code (IMPORT) */
/* Source File: 2014 2015 2016 Merge AGS-Exames 19-02-18 ELEGIVEIS_CCP_PCR_ALB_EXAMES_ LIMPO_24.04.sav */
/* Source Path: /home/isaias.prestes/Data */
/* Code generated on: 30/05/18 09:37 */

%web_drop_table(WORK.ALLDATA);


FILENAME REFFILE '/home/isaias.prestes/Data/2014 2015 2016 Merge AGS-Exames 19-02-18 ELEGIVEIS_CCP_PCR_ALB_EXAMES_ LIMPO_24.04.sav';

PROC IMPORT DATAFILE=REFFILE
	DBMS=SAV
	OUT=WORK.ALLDATA;
RUN;

PROC CONTENTS DATA=WORK.ALLDATA; RUN;


%web_open_table(WORK.ALLDATA);

LIBNAME GEORGIA V9 '/home/isaias.prestes/Data' ;

******************
* Exploring data *
******************;

PROC SQL;
	CREATE TABLE INSP_EXAM AS
	SELECT DISTINCT EXAME_DIAGNOSTICO FROM ALLDATA ;
QUIT;

* FLAGS PARA OS MERGE ;
DATA TAB_Merge ;
	SET ALLDATA ;
	
	FLAG_DIABETES = 0 ;
	IF PRXMATCH('/DIABETES MELLITUS/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_DIABETES = 1 ;
	LABEL FLAG_DIABETES="Diabetes" ;

	FLAG_RESPIRATORIAS = 0 ;
	IF PRXMATCH('/ ASMA|ASMA /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/PULMONAR/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/PLEURA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/PNEUMO/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/RESPIR/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/BRONQU/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/ ENFISEMA|ENFISEMA /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/ RINITE|RINITE /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/ PULMÃO|PULMÃO /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/ PULMAO|PULMAO /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/VIAS AEREAS/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	IF PRXMATCH('/xxxxx/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RESPIRATORIAS = 1 ;
	LABEL FLAG_RESPIRATORIAS="Doenças Respiratórias" ;
	
	FLAG_CARDIOVACULAR = 0 ;
	IF PRXMATCH('/ ANGINA|ANGINA /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/CARDIAC/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/CARDIO/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/CARDITE/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ATEROSCLERO/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/CORACAO/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ INFARTO|INFARTO /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ ATRIOVENTRICULAR|ATRIOVENTRICULAR /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/AORT/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ CAROTIDA|CAROTIDA /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ BRADICARDIA|BRADICARDIA /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/VALVA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/VENTRICULAR/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ARTER/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/COMPLICACAO MECANICA DE DISPOSITIVO ELETRONICO CARDIA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/DOENCA DE CHAGAS (CRONICA) COM COMPROMETIMENTO CARDIA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ VASCULARES|VASCULARES /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ MITRAL|MITRAL /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ ATRIAL|ATRIAL /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/MARCA PASSO/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/INSUFICIENCIA VENOSA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/TRICUSPIDE;/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/ ANGIOPLASTIA|ANGIOPLASTIA /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	IF PRXMATCH('/OUTROS TRANSTORNOS DO APARELHO CIRCULATORIO SUBSEQUEN/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ;
	LABEL FLAG_CARDIOVACULAR="Doenças Cardiovasculares" ;

	FLAG_HIPERTENSAO = 0 ;
	IF PRXMATCH('/HIPERTENSAO ESSENCIAL/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_HIPERTENSAO = 1 ;
	LABEL FLAG_HIPERTENSAO="Hipertensão" ;

	FLAG_HEPATICAS = 0 ;
	IF PRXMATCH('/HEPATIC/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_HEPATICAS = 1 ;
	IF PRXMATCH('/FIGADO/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_HEPATICAS = 1 ;
	IF PRXMATCH('/ENCEFALOPATIA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_HEPATICAS = 1 ;
	IF PRXMATCH('/HEPATITE/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_HEPATICAS = 1 ;
	IF PRXMATCH('/HEPATOMEGALIA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_HEPATICAS = 1 ;
	IF PRXMATCH('/HIPERTENSAO PORTAL/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_HEPATICAS = 1 ;
	LABEL FLAG_HEPATICAS="Doenças Hepáticas" ;

	FLAG_RENAIS = 0 ;
	IF PRXMATCH('/NEFRITICA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/NEFROTICA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/RENAL/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/URETER/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/RIM /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/ RIM/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/ CISTITE|CISTITE /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/ PIONEFROSE|PIONEFROSE /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/URINAR/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/DIALISE/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/DISURIA;/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/URETRAL/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/ HEMATURIA|HEMATURIA /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/URINARIO/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/NEFRITE/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/ NEFROPATIA|NEFROPATIA /', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/OUTRAS DIALISES/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	IF PRXMATCH('/ANURIA E OLIGURIA/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_RENAIS = 1 ;
	LABEL FLAG_RENAIS="Doenças Renais" ;

/* 	FLAG_CARDIOVACULAR = 0 ; */
/* 	IF PRXMATCH('/xxxxx/', STRIP(UPCASE(EXAME_DIAGNOSTICO)))>0 THEN FLAG_CARDIOVACULAR = 1 ; */
/* 	LABEL FLAG_CARDIOVACULAR="Doenças Respiratórias" ; */
	
	DIF_INTER_EXAME = DATDIF(DATAINTERNACAO, DATAPEDIDO, 'ACT/ACT') ;
	LABEL DIF_INTER_EXAME="Dias entre Pedido e Internação" ;
RUN;

PROC FREQ data=TAB_Merge ;
	TABLE FLAG_DIABETES FLAG_RESPIRATORIAS FLAG_CARDIOVACULAR FLAG_HIPERTENSAO FLAG_HEPATICAS FLAG_RENAIS ;
RUN;

title 'Investigacao - Hipertensão';
PROC FREQ data=TAB_Merge ;
	TABLE EXAME_DIAGNOSTICO ;
	WHERE FLAG_HIPERTENSAO = 1 ;
RUN;

title 'Investigacao - Respiratórias';
PROC FREQ data=TAB_Merge ;
	TABLE EXAME_DIAGNOSTICO ;
	WHERE FLAG_RESPIRATORIAS = 1 ;
RUN;

title;

DATA GEORGIA.Merge_FLAGS ;
	SET TAB_Merge ;
RUN;

